[general]
import = [ "~/.dotfiles/alacritty/dracula.toml" ]

[env]
TERM = "xterm-256color"

[font]
size = 14

[font.normal]
family = "JetBrainsMono Nerd Font Mono"

[keyboard]
bindings = [
    { key = "Key0", mods = "Command", action = "ResetFontSize" },
    { key = "Equals", mods = "Command", action = "IncreaseFontSize" },
    { key = "Plus", mods = "Command", action = "IncreaseFontSize" },
    { key = "Minus", mods = "Command", action = "DecreaseFontSize" },
    { key = "H", mods = "Command", action = "Hide" },
    { key = "M", mods = "Command", action = "Minimize" },
    { key = "Q", mods = "Command", action = "Quit" },
    { key = "W", mods = "Command", action = "Quit" },
    { key = "N", mods = "Command", action = "CreateNewWindow" },
    { key = "F", mods = "Command", action = "ToggleFullscreen" },
    { key = "Space", mods = "Command|Shift", action = "ToggleViMode"},
]

[window]
decorations = "None"
decorations_theme_variant = "None"
startup_mode = "Windowed"
opacity = 0.5
blur = true

[window.padding]
x = 25
y = 25

[scrolling]
history = 10000
multiplier = 3

[cursor]
thickness = 0.4

[cursor.style]
shape = "Beam"
blinking = "On"

[cursor.vi_mode_style]
shape = "Block"
blinking = "Off"

[mouse]
hide_when_typing = true
